# Generated by Django 5.2.6 on 2025-09-30 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('Planting', 'Planting'), ('Cultural', 'Cultural'), ('Historical', 'Historical'), ('Economic', 'Economic Value')], max_length=50)),
                ('description', models.TextField()),
            ],
        ),
    ]
