# Generated by Django 5.2.6 on 2025-10-02 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='section',
            options={'verbose_name': 'Educational Section', 'verbose_name_plural': 'Educational Sections'},
        ),
        migrations.AddField(
            model_name='section',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='section_images/'),
        ),
    ]
