# Generated by Django 5.2.6 on 2025-10-13 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0004_alter_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='attachments/'),
        ),
        migrations.AddField(
            model_name='section',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
