# Generated by Django 5.2.6 on 2025-10-23 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0005_section_attachment_section_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='FestivalEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('event_type', models.CharField(choices=[('Parade', 'Parade'), ('Competition', 'Competition'), ('Concert', 'Concert'), ('Exhibit', 'Exhibit'), ('Trade Fair', 'Trade Fair'), ('Religious', 'Religious'), ('Other', 'Other')], default='Other', max_length=50)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('time', models.TimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('map_link', models.URLField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='festival_events/')),
            ],
        ),
    ]
