# Generated by Django 5.2.6 on 2025-10-26 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0006_festivalevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='blocked_until',
            field=models.DateTimeField(blank=True, help_text='Account blocked until this timestamp', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='failed_login_attempts',
            field=models.IntegerField(default=0, help_text='Number of consecutive failed login attempts'),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_failed_login',
            field=models.DateTimeField(blank=True, help_text='Timestamp of last failed login attempt', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('blocked', 'Blocked')], default='active', help_text='User account status', max_length=10),
        ),
    ]
