# Generated by Django 5.2.6 on 2025-10-26 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0007_profile_blocked_until_profile_failed_login_attempts_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('color', models.CharField(default='planting', max_length=50)),
                ('custom_color', models.CharField(blank=True, help_text='Hex color code (e.g., #FF5733)', max_length=7, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
    ]
