# Generated by Django 5.2.6 on 2025-10-26 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0008_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='color',
        ),
        migrations.RemoveField(
            model_name='category',
            name='custom_color',
        ),
    ]
