# Generated by Django 5.2.7 on 2025-10-28 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0010_question_answer_quiz_question_quiz'),
    ]

    operations = [
        migrations.CreateModel(
            name='MinasaProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('product_name', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Minasa Product',
                'verbose_name_plural': 'Minasa Products',
                'ordering': ['-id'],
            },
        ),
    ]
