# Generated by Django 5.2.7 on 2025-10-28 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0011_minasaproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='minasaproduct',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
