# Generated by Django 5.2.7 on 2025-10-31 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0012_minasaproduct_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='MinigameLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(upload_to='minigame/')),
                ('image2', models.ImageField(upload_to='minigame/')),
                ('image3', models.ImageField(upload_to='minigame/')),
                ('image4', models.ImageField(upload_to='minigame/')),
                ('answer', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Minigame Level',
                'verbose_name_plural': 'Minigame Levels',
                'ordering': ['-created_at'],
            },
        ),
    ]
