# Generated by Django 5.2.6 on 2025-10-31 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0013_minigamelevel'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrowthStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('date', models.DateField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='growth_timeline/')),
                ('order', models.PositiveIntegerField(blank=True, help_text='Optional manual ordering', null=True)),
            ],
            options={
                'ordering': ['date', 'order'],
            },
        ),
    ]
