# Generated by Django 5.2.7 on 2025-11-02 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0014_growthstage'),
    ]

    operations = [
        migrations.AddField(
            model_name='minigamelevel',
            name='attempts',
            field=models.PositiveIntegerField(default=0, help_text='Number of times this level has been attempted'),
        ),
    ]
