# Generated by Django 5.2.6 on 2025-11-15 17:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0017_fileaccesslog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='fileaccesslog',
            new_name='sections_fi_section_fe925f_idx',
            old_name='sections_fi_section_8b7a9c_idx',
        ),
        migrations.RenameIndex(
            model_name='fileaccesslog',
            new_name='sections_fi_user_id_389f96_idx',
            old_name='sections_fi_user_id_9f8b2d_idx',
        ),
        migrations.AlterField(
            model_name='fileaccesslog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='file_access_logs', to=settings.AUTH_USER_MODEL),
        ),
    ]
